### 📌 Problem Statement

### 🎯 Why

In the modern football industry, accurately estimating a player's market value is crucial for clubs during transfers, scouting, and team building. Player valuation depends on multiple factors such as technical skills, physical attributes, performance metrics, and potential, making it a complex and data-intensive task.
Traditional evaluation methods are often subjective and inconsistent, leading to inefficient decision-making. Therefore, there is a need for a data-driven solution that can analyze player attributes and provide reliable market value predictions.

In [1]:
import numpy as np
import pandas as pd

### 📂 Step 1: Importing and Understanding the Data

Before building any Machine Learning model, it is essential to understand the dataset thoroughly. This step helps us identify the structure, data types, missing values, and overall distribution of the data.
By exploring the dataset, we can:
Detect inconsistencies and errors early
Understand which features are useful for prediction
Identify categorical and numerical columns
Get insights into the target variable (player value)
This ensures that all further preprocessing and modeling steps are based on a clear understanding of the data, leading to better and more reliable results.

In [2]:
df=pd.read_csv("fifa.csv")

/var/folders/nj/6825lt1517x15w7zcvyc04m00000gn/T/ipykernel_21053/1875175658.py:1: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("fifa.csv")

In [3]:
df.shape

(18979, 77)

In [4]:
df.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [5]:
df.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [6]:
df.describe()

,ID,Age,↓OVA,POT,BOV,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,...,GK Positioning,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY
count,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,...,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000
mean,226403.384794,25.194109,65.718636,71.136414,66.751726,248.938142,49.688392,45.842405,51.942726,58.768112,...,16.217187,16.519627,1595.286949,355.702197,67.453975,53.457031,57.681016,62.875020,49.866221,64.368934
std,27141.054157,4.710520,6.968999,6.114635,6.747193,74.299428,18.131153,19.567081,17.294409,14.519106,...,17.002239,17.854079,269.874789,40.761117,10.677859,13.827425,10.081857,9.927415,16.443213,9.601883
min,41.000000,16.000000,47.000000,47.000000,48.000000,42.000000,6.000000,3.000000,5.000000,7.000000,...,2.000000,2.000000,747.000000,232.000000,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000
25%,210135.000000,21.000000,61.000000,67.000000,62.000000,222.000000,38.000000,30.000000,44.000000,54.000000,...,8.000000,8.000000,1452.000000,327.000000,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000
50%,232418.000000,25.000000,66.000000,71.000000,67.000000,263.000000,54.000000,49.000000,55.000000,62.000000,...,11.000000,11.000000,1627.000000,356.000000,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000
75%,246922.500000,29.000000,70.000000,75.000000,71.000000,297.000000,63.000000,62.000000,64.000000,68.000000,...,14.000000,14.000000,1781.000000,384.000000,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000
max,259216.000000,53.000000,93.000000,95.000000,93.000000,437.000000,94.000000,95.000000,93.000000,94.000000,...,91.000000,90.000000,2316.000000,498.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(54), object(23)
memory usage: 11.1+ MB

In [8]:
pd.set_option('display.max_columns', None)
df.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,Right,91,CAM,"Aug 30, 2015",NaN,€129M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,Right,91,LW,"Aug 3, 2017",NaN,€132M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,595

In [9]:
print(df['Height'].unique())
print(df['Weight'].unique())
print(df['W/F'].unique())

['170cm' '187cm' '188cm' '181cm' '175cm' '184cm' '191cm' '178cm' '193cm'
 '185cm' '199cm' '173cm' '168cm' '176cm' '177cm' '183cm' '180cm' '189cm'
 '179cm' '195cm' '172cm' '182cm' '186cm' '192cm' '165cm' '194cm' '167cm'
 '196cm' '163cm' '190cm' '174cm' '169cm' '171cm' '197cm' '200cm' '166cm'
 '6\'2"' '164cm' '198cm' '6\'3"' '6\'5"' '5\'11"' '6\'4"' '6\'1"' '6\'0"'
 '5\'10"' '5\'9"' '5\'6"' '5\'7"' '5\'4"' '201cm' '158cm' '162cm' '161cm'
 '160cm' '203cm' '157cm' '156cm' '202cm' '159cm' '206cm' '155cm']
['72kg' '83kg' '87kg' '70kg' '68kg' '80kg' '71kg' '91kg' '73kg' '85kg'
 '92kg' '69kg' '84kg' '96kg' '81kg' '82kg' '75kg' '86kg' '89kg' '74kg'
 '76kg' '64kg' '78kg' '90kg' '66kg' '60kg' '94kg' '79kg' '67kg' '65kg'
 '59kg' '61kg' '93kg' '88kg' '97kg' '77kg' '62kg' '63kg' '95kg' '100kg'
 '58kg' '183lbs' '179lbs' '172lbs' '196lbs' '176lbs' '185lbs' '170lbs'
 '203lbs' '168lbs' '161lbs' '146lbs' '130lbs' '190lbs' '174lbs' '148lbs'
 '165lbs' '159lbs' '192lbs' '181lbs' '139lbs' '154lbs' '157lbs' '163lbs'
 '98kg' '103kg' '99kg' '102kg' '56kg' '101kg' '57kg' '55kg' '104kg'
 '107kg' '110kg' '53kg' '50kg' '54kg' '52kg']
['4 ★' '3 ★' '5 ★' '2 ★' '1 ★']

In [10]:
df[['Value', 'Wage', 'Release Clause']].head()

     Value   Wage Release Clause
0  €103.5M  €560K        €138.4M
1     €63M  €220K         €75.9M
2    €120M  €125K        €159.4M
3    €129M  €370K          €161M
4    €132M  €270K        €166.5M

In [11]:
print(df['Club'].head().values)

['\n\n\n\nFC Barcelona' '\n\n\n\nJuventus' '\n\n\n\nAtlético Madrid'
 '\n\n\n\nManchester City' '\n\n\n\nParis Saint-Germain']

### Data Quality Issues Identified

1.Inconsistent Units (Height/Weight): The Height column mixes "cm" with "feet/inches" (e.g., "5'7" vs "170cm"), and Weight mixes "kg" with "lbs".

2.Currency Formatting (Value, Wage, Release Clause): Financial columns are stored as object strings with currency symbols ('€') and suffixes ('K', 'M') instead of numeric values (e.g., "€100M").

3.Embedded Characters: Columns like W/F, SM, and IR contain unnecessary special characters (e.g., "4 ★") preventing numerical analysis.

4.Hidden Newlines: The Club column contains hidden newline characters (\n) at the start of string values.

5.Incorrect Data Types: The Joined column is stored as a string rather than a datetime object, making time-based calculations impossible.

6.Mixed Data Types: Column 76 (Loan Date End) contains mixed types, causing memory warnings during load.

7.Redundant Columns: The Contract column duplicates information available in Joined and Contract Valid Until, and requires parsing to be useful.

In [12]:
def convert_height(height):
    if "cm" in height:
        return int(height.replace("cm",""))
    elif "'" in height:
        # Split 5'7" into [5, 7]
        feet,inches = height.split("'")
        inches = inches.replace("\"", "") 

        # Math: (Feet * 30.48) + (Inches * 2.54)
        return round((int(feet) * 30.48) + (int(inches) * 2.54))
    else:
        return height

# 2. Apply it to the Height column
df['Height'] = df['Height'].apply(convert_height)

# 3. Rename column to be specific
df.rename(columns={'Height': 'Height_cm'}, inplace=True)

# 4. Verify
print(df['Height_cm'].head())
print(df['Height_cm'].unique())

0    170
1    187
2    188
3    181
4    175
Name: Height_cm, dtype: int64
[170 187 188 181 175 184 191 178 193 185 199 173 168 176 177 183 180 189
 179 195 172 182 186 192 165 194 167 196 163 190 174 169 171 197 200 166
 164 198 201 158 162 161 160 203 157 156 202 159 206 155]

In [13]:
def convert_weight(weight):
    if "kg" in weight:
        return int(weight.replace("kg", ""))
    elif "lbs" in weight:
        lbs = int(weight.replace("lbs", ""))
        return round(lbs * 0.453592) # Standard conversion
    else:
        return weight


df['Weight'] = df['Weight'].apply(convert_weight)


df.rename(columns={'Weight': 'Weight_kg'}, inplace=True)

# 4. Verify
print(df['Weight_kg'].head())
print(df['Weight_kg'].unique())

0    72
1    83
2    87
3    70
4    68
Name: Weight_kg, dtype: int64
[ 72  83  87  70  68  80  71  91  73  85  92  69  84  96  81  82  75  86
  89  74  76  64  78  90  66  60  94  79  67  65  59  61  93  88  97  77
  62  63  95 100  58  98 103  99 102  56 101  57  55 104 107 110  53  50
  54  52]

In [14]:
def convert_money(value):

    if pd.isna(value):
        return 0

    value = value.replace('€', '').strip()

    if 'M' in value:
        value = value.replace('M','')
        return float(value) * 1_000_000

    if 'K' in value:
        value = value.replace('K','')
        return float(value) * 1_000

    else:
        return float(value)

In [15]:
cols_to_clean = ['Value', 'Wage', 'Release Clause']

for col in cols_to_clean:
    df[col] = df[col].apply(convert_money)

# Check the results.
print(df[cols_to_clean].head())
print("New Data Types:")
print(df[cols_to_clean].dtypes)

         Value      Wage  Release Clause
0  103500000.0  560000.0     138400000.0
1   63000000.0  220000.0      75900000.0
2  120000000.0  125000.0     159400000.0
3  129000000.0  370000.0     161000000.0
4  132000000.0  270000.0     166500000.0
New Data Types:
Value             float64
Wage              float64
Release Clause    float64
dtype: object

In [16]:
print(df['W/F'].unique())

star_cols = ['W/F', 'SM', 'IR']

for col in star_cols:
    df[col] = df[col].astype(str).str.replace('★', '').str.strip().astype(int)

# 4. Verify the results
print(df[star_cols].head())
print("New Data Types:")
print(df[star_cols].dtypes)

['4 ★' '3 ★' '5 ★' '2 ★' '1 ★']
   W/F  SM  IR
0    4   4   5
1    4   5   5
2    3   1   3
3    5   4   4
4    5   5   5
New Data Types:
W/F    int64
SM     int64
IR     int64
dtype: object

In [17]:
# 1. Check the mess (printing values helps see the \n)

print("Before Cleaning (First 5 Clubs):")
print(df['Club'].head())

# 2. Apply strip() to remove leading/trailing whitespace & newlines

df['Club'] = df['Club'].str.strip()

# 3. Verify

print("After Cleaning:")
print(df['Club'].head())
print("Unique Names:")
print(df['Club'].unique())

Before Cleaning (First 5 Clubs):
0           \n\n\n\nFC Barcelona
1               \n\n\n\nJuventus
2        \n\n\n\nAtlético Madrid
3        \n\n\n\nManchester City
4    \n\n\n\nParis Saint-Germain
Name: Club, dtype: object
After Cleaning:
0           FC Barcelona
1               Juventus
2        Atlético Madrid
3        Manchester City
4    Paris Saint-Germain
Name: Club, dtype: object
Unique Names:
['FC Barcelona' 'Juventus' 'Atlético Madrid' 'Manchester City'
 'Paris Saint-Germain' 'FC Bayern München' 'Liverpool' 'Real Madrid'
 'Chelsea' 'Tottenham Hotspur' 'Inter' 'Napoli' 'Borussia Dortmund'
 'Manchester United' 'Arsenal' 'Lazio' 'Leicester City'
 'Borussia Mönchengladbach' 'Real Sociedad' 'Atalanta'
 'Olympique Lyonnais' 'Milan' 'Villarreal CF' 'RB Leipzig' 'Cagliari'
 'Ajax' 'SL Benfica' 'AS Monaco' 'Wolverhampton Wanderers' 'Everton'
 'Fiorentina' 'FC Porto' 'RC Celta' 'Torino' 'Sevilla FC' 'Grêmio'
 'Real Betis' 'Roma' 'Newcastle United' 'Eintracht Frankfurt'
 'Valencia CF' 'Medipol Başakşehir FK' 'Inter Miami' 'Bayer 04 Leverkusen'
 'Levante UD' 'Crystal Palace' 'Athletic Club de Bilbao'
 'Shanghai SIPG FC' 'VfL Wolfsburg' 'Guangzhou Evergrande Taobao FC'
 'Al Shabab' 'Olympique de Marseille' 'Los Angeles FC'
 'Beijing Sinobo Guoan FC' 'Getafe CF' 'SV Werder Bremen'
 'TSG 1899 Hoffenheim' 'LOSC Lille' 'Deportivo Alavés' 'Burnley'
 'Leeds United' 'Fulham' 'PFC CSKA Moscow' 'Genoa' 'Galatasaray SK'
 'Atlanta United' 'Atlético Mineiro' 'Flamengo' 'Palmeiras' 'No Club'
 'São Paulo' 'West Ham United' 'SD Eibar' 'River Plate' 'OGC Nice'
 'Real Valladolid CF' 'Sporting CP' 'PSV' 'Feyenoord' 'Club Brugge KV'
 'Shakhtar Donetsk' 'Vissel Kobe' 'Boca Juniors' '1. FC Union Berlin'
 'Dalian YiFang FC' 'AS Saint-Étienne' 'Sassuolo' 'Tigres U.A.N.L.'
 'Dinamo Zagreb' 'Dynamo Kyiv' 'Fluminense' 'Udinese' 'Aston Villa'
 'Stade Rennais FC' 'Beşiktaş JK' 'Brighton & Hove Albion'
 'Hebei China Fortune FC' 'Southampton' 'Lokomotiv Moscow'
 'Jiangsu Suning FC' 'Al Hilal' 'West Bromwich Albion' 'Fenerbahçe SK'
 'FC Groningen' 'Guangzhou R&F FC' 'Orlando City SC' 'Sampdoria'
 'Stade de Reims' 'Sheffield United' 'Santos' 'Internacional' 'Coritiba'
 'CA Osasuna' 'LA Galaxy' 'Al Nassr' 'SC Freiburg' 'SC Braga'
 'Olympiacos CFP' 'Toronto FC' 'Granada CF' 'FC Schalke 04'
 'RC Strasbourg Alsace' 'Hertha BSC' 'AZ Alkmaar' 'Seattle Sounders FC'
 'Montpellier HSC' 'Shanghai Greenland Shenhua FC' 'Hamburger SV'
 'Girona FC' 'Racing Club' 'Portland Timbers' 'FC Girondins de Bordeaux'
 'Watford' 'Estudiantes de La Plata' 'Club América' 'Vitória Guimarães'
 'SK Slavia Praha' 'Trabzonspor' 'RCD Espanyol' 'FC Nantes' 'Angers SCO'
 'Cruz Azul' 'BSC Young Boys' 'Club León' 'Spartak Moscow' 'Sivasspor'
 'Elche CF' 'FC Augsburg' 'Wuhan Zall' 'Parma' 'Royal Antwerp FC'
 'Monterrey' 'San Lorenzo de Almagro' 'AC Monza' 'Club Atlético Lanús'
 'SD Huesca' 'Derby County' 'Kayserispor' 'RSC Anderlecht' 'CD Leganés'
 'Vélez Sarsfield' 'Stade Brestois 29' 'Tianjin TEDA FC' 'Birmingham City'
 'Hellas Verona' '1. FC Köln' 'Al Wehda' 'Bournemouth' 'Alanyaspor'
 'Bologna' 'Amiens SC' 'Celtic' 'Shijiazhuang Ever Bright F.C.'
 'Club Atlas' 'Al Ahli' 'Norwich City' 'Fatih Karagümrük S.K.'
 'Club Tijuana' 'Universidad Católica' 'Goiás' 'Benevento' 'Independiente'
 'Qingdao Huanghai F.C.' 'Brentford' 'AEK Athens' 'Racing Club de Lens'
 'Olimpia Asunción' 'Shenzhen FC' 'Çaykur Rizespor' 'KAA Gent'
 'New England Revolution' 'Cádiz CF' '1. FSV Mainz 05' 'Vasco da Gama'
 'FC Midtjylland' 'Al Ain FC' 'Santos Laguna' 'SPAL' 'Perth Glory'
 'FC Utrecht' 'Montreal Impact' 'UD Almería' 'Fortaleza' 'Spezia'
 'FC Basel 1893' 'FC København' 'Godoy Cruz' 'Deportivo Toluca'
 'Nacional de Montevideo' 'Aalborg BK' 'Rio Ave FC' 'FC Metz'
 'Chongqing Dangdai Lifan FC SWM Team' 'Rosenborg BK'
 'FC Red Bull Salzburg' 'Botafogo' 'DSC Arminia Bielefeld'
 'Club Athletico Paranaense' 'RCD Mallorca' 'Pachuca' 'Swansea City'
 'KRC Genk' 'En Avant de Guingamp' 'Lecce' 'Nîmes Olympique' 'Colo-Colo'
 'Stade Malherbe Caen' 'Columbus Crew SC' 'Junior FC' 'VfB Stuttgart'
 'Moreirense FC' 'Rangers FC' 'Malmö FF' 'Shandong Luneng TaiShan FC'
 'Sparta Praha' 'Hatayspor' 'Chicago Fire' 'Toulouse Football Club'
 'FC Seoul' 'Antalyaspor' 'Deportivo Cali' 'Kaizer Chiefs' 'Real Zaragoza'
 'Atlético Clube Goianiense' 'Puebla FC' 'Fortuna Düsseldorf'
 'Western United FC' 'Astra Giurgiu' 'Henan Jianye FC' 'Bahia' 'Famalicão'
 'Atiker Konyaspor' 'Peñarol' 'DC United' 'New York City FC'
 'Argentinos Juniors' 'U.N.A.M.' 'Minnesota United FC' 'Nottingham Forest'
 'Independiente del Valle' 'Defensa y Justicia' 'Philadelphia Union'
 "Newell's Old Boys" 'Rosario Central' 'Atlético de San Luis' 'FC Dallas'
 'Denizlispor' 'Yeni Malatyaspor' 'Club Atlético Colón' 'Houston Dynamo'
 'Millwall' 'Clube Sport Marítimo' 'MKE Ankaragücü' 'Guadalajara'
 'Boavista FC' 'Sporting Kansas City' 'Atlético Nacional' 'CD Lugo'
 'New York Red Bulls' 'PAOK' 'SC Heerenveen' 'Daegu FC'
 'Preston North End' 'Damac FC' 'Brescia' 'VfL Bochum 1848'
 'Vancouver Whitecaps FC' 'SV Sandhausen' 'Royal Excel Mouscron'
 'Dijon FCO' 'Molde FK' 'Panathinaikos FC' 'LASK Linz' 'Ulsan Hyundai FC'
 'Real Salt Lake' 'FC Luzern' 'Viktoria Plzeň' 'Orlando Pirates'
 'Al Ittihad' '1. FC Nürnberg' 'Standard de Liège' 'Rayo Vallecano'
 'Club Libertad' 'Jeonbuk Hyundai Motors' 'Western Sydney Wanderers'
 'Unión de Santa Fe' 'FC Sion' 'Sydney FC' 'Hannover 96'
 'Real Sporting de Gijón' 'FC Cincinnati' 'ESTAC Troyes'
 'San Jose Earthquakes' 'Club Guaraní' 'FC Lorient' 'Gençlerbirliği SK'
 'Sporting de Charleroi' 'Wisła Kraków' 'Al Taawoun' 'Reading'
 'Gazişehir Gaziantep F.K.' 'Blackburn Rovers' 'Kashiwa Reysol'
 'FK Bodø/Glimt' 'Willem II' 'Vitesse' 'Gil Vicente FC' 'SønderjyskE'
 'Yokohama F. Marinos' 'FC St. Gallen' 'Club Atlético Aldosivi'
 'Göztepe SK' 'Holstein Kiel' 'FC Juárez' 'FCSB (Steaua)' 'Ettifaq FC'
 'KAS Eupen' 'FC Tokyo' 'Melbourne City FC' 'Universitatea Craiova'
 'CD Tondela' 'Wolfsberger AC' 'Ceará Sporting Club'
 'River Plate Asunción' 'Stoke City' 'Paris FC' 'IFK Norrköping' 'Crotone'
 'Cardiff City' 'América de Cali' 'Al Faisaly' 'Independiente Medellín'
 'Portimonense SC' 'CD Tenerife' 'Heracles Almelo' 'Nashville SC'
 'SK Rapid Wien' 'Kawasaki Frontale' 'Club Necaxa' 'Chievo Verona'
 'Lech Poznań' 'AIK' 'FK Austria Wien' 'Querétaro' '1. FC Heidenheim 1846'
 'Legia Warszawa' 'Club Atlético Banfield' 'Os Belenenses'
 'Huddersfield Town' 'KSV Cercle Brugge' 'LDU Quito'
 'Gimnasia y Esgrima La Plata' 'Gamba Osaka' 'Middlesbrough' 'Servette FC'
 'Empoli' 'Real Oviedo' 'Kasimpaşa SK' 'CFR Cluj' 'Millonarios FC'
 'FC Paços de Ferreira' 'Sint-Truidense VV' 'AD Alcorcón'
 'Colorado Rapids' 'Dinamo Bucureşti' 'Cerezo Osaka' 'FC Emmen'
 'Sheffield Wednesday' 'FC Erzgebirge Aue' 'Raków Częstochowa'
 'Atlético Tucumán' 'SV Darmstadt 98' 'Bristol City' 'Oud-Heverlee Leuven'
 'Barnsley' 'Queens Park Rangers' 'Sangju Sangmu FC' 'Helsingborgs IF'
 'AC Ajaccio' 'Oceânico FC' 'Club Atlético Talleres' 'Al Hazem'
 'SC Paderborn 07' 'Club Atlético Huracán' 'KV Kortrijk' 'El Nacional'
 'Mazatlán FC' 'Aberdeen' 'CD Mirandés' 'SV Zulte-Waregem' 'Piast Gliwice'
 'Djurgårdens IF' 'Central Córdoba' 'Wellington Phoenix'
 'Deportivo Binacional' 'Patronato' 'SpVgg Greuther Fürth' 'IFK Göteborg'
 'FC Cartagena' 'Santa Clara' 'FC Twente' 'Farense' 'ADO Den Haag'
 'AJ Auxerre' 'Al Fateh' 'Valenciennes FC' 'Hokkaido Consadole Sapporo'
 'FC St. Pauli' 'Albacete BP' '1. FC Kaiserslautern' 'Al Fayha'
 'Incheon United FC' 'KV Mechelen' 'Pohang Steelers' 'CD Nacional'
 'Unión La Calera' 'BB Erzurumspor' 'Kashima Antlers' 'Arsenal de Sarandí'
 'HJK Helsinki' 'Karlsruher SC' 'Aarhus GF' 'FC Zürich'
 'Barcelona Sporting Club' 'SG Dynamo Dresden' 'Sanfrecce Hiroshima'
 'Al Raed' 'SD Ponferradina' 'Brøndby IF' 'Lechia Gdańsk' 'FC Viitorul'
 'SK Sturm Graz' 'IF Elfsborg' 'Gangwon FC' 'Melgar FBC'
 'Club Atlético Grau' 'Jagiellonia Białystok' 'Waasland-Beveren'
 'VfL Osnabrück' 'Nagoya Grampus' 'CF Fuenlabrada' 'Shamrock Rovers'
 'Shimizu S-Pulse' 'RKC Waalwijk' 'Vålerenga Fotball' 'Clermont Foot 63'
 'FC Ingolstadt 04' 'FC Würzburger Kickers' 'Górnik Zabrze'
 'Charlton Athletic' 'Beerschot AC' 'Coquimbo Unido' 'Viktoria Köln'
 'Hull City' 'Málaga CF' 'FC Nordsjælland' 'UD Las Palmas' 'VVV-Venlo'
 'GwangJu FC' 'Chamois Niortais Football Club' 'FC Lugano' 'Cusco FC'
 'Sparta Rotterdam' 'Sol de América' 'PEC Zwolle' 'Pogoń Szczecin'
 'Doncaster Rovers' 'Kristiansund BK' 'Liverpool Fútbol Club'
 'Club Bolívar' 'Urawa Red Diamonds' 'SK Brann' 'Eintracht Braunschweig'
 'Nacional Asunción' 'Melbourne Victory' 'Kilmarnock' 'Dundalk'
 'SSV Jahn Regensburg' 'Abha Club' 'Club Atlético Tigre'
 'Suwon Samsung Bluewings' 'Shonan Bellmare' 'SD Aucas' 'Emelec'
 'Fortuna Sittard' 'La Berrichonne de Châteauroux' 'Śląsk Wrocław'
 'Coventry City' 'Sunderland' 'Alianza Lima' 'Hammarby IF' 'Cracovia'
 'CE Sabadell FC' 'Oita Trinita' 'BK Häcken' 'Luton Town' 'Le Havre AC'
 'IK Sirius' 'Zagłębie Lubin' 'Grenoble Foot 38' 'Macarthur FC'
 'Rodez Aveyron Football' 'Vegalta Sendai' 'Motherwell'
 'SV Wehen Wiesbaden' 'Audax Italiano' 'Gaz Metan Mediaş' 'Portsmouth'
 'Hibernian' 'Always Ready' 'UD Logroñés' 'FC Voluntari' 'FC Hermannstadt'
 'AS Nancy Lorraine' 'Rotherham United' 'Fleetwood Town'
 'Jorge Wilstermann' 'Odense Boldklub' 'MSV Duisburg'
 'FC Sochaux-Montbéliard' 'Milton Keynes Dons' 'River Plate Montevideo'
 'Delfín SC' 'Universidad Católica del Ecuador' 'Deportivo Pasto'
 'KV Oostende' 'Club Plaza Colonia' 'Wigan Athletic' 'FC Botoşani'
 'C.D. Castellón' 'SCR Altach' 'Örebro SK' 'TSV Hartberg' 'Stabæk Fotball'
 'Wycombe Wanderers' 'St. Johnstone FC' 'Oxford United' 'Lincoln City'
 'Randers FC' 'Viking FK' 'FC Chambly Oise' 'Dundee United'
 'Oriente Petrolero' 'Odds BK' 'Nacional Potosí' 'Sepsi OSK'
 'FC Hansa Rostock' 'Lyngby BK' 'SpVgg Unterhaching' 'Brisbane Roar'
 'Seongnam FC' 'SV Ried' 'CD Huachipato' 'WSG Tirol'
 'Podbeskidzie Bielsko-Biała' 'Peterborough United' 'Club Blooming'
 'Wisła Płock' 'Busan IPark' 'FSV Zwickau' 'Mjøndalen IF' 'Vejle Boldklub'
 'Pau FC' 'FC Lausanne-Sport' 'Estudiantes de Mérida' 'Sagan Tosu'
 'SV Waldhof Mannheim' 'Sport Huancayo' 'Hallescher FC' 'Kalmar FF'
 'St. Mirren' 'SKN St. Pölten' 'Sarpsborg 08 FF' 'Shrewsbury'
 'TSV 1860 München' 'SV Meppen' 'Ipswich Town' 'IK Start'
 'Adelaide United' 'Stal Mielec' 'Centro Atlético Fénix' 'Newcastle Jets'
 'Livingston FC' 'AC Mineros de Guayana' 'AFC Wimbledon' 'Burton Albion'
 'Al Adalah' 'Warta Poznań' 'USL Dunkerque' 'Bristol Rovers' 'UTA Arad'
 'Östersunds FK' 'Sportivo Luqueño' 'Politehnica Iaşi' 'Salford City'
 'Central Coast Mariners' 'Caracas FC' 'AC Horsens' 'Plymouth Argyle'
 'Aalesunds FK' 'Crewe Alexandra' 'Chindia Târgovişte' 'Oldham Athletic'
 'Yokohama FC' 'Blackpool' 'Northampton Town' 'Bayern München II'
 'FK Haugesund' 'KFC Uerdingen 05' 'Forest Green Rovers' 'Cheltenham Town'
 'Strømsgodset IF' 'Mjällby AIF' 'Exeter City' 'Cambridge United'
 'Grimsby Town' 'FC Vaduz' 'Türkgücü München' 'VfB Lübeck'
 'Bolton Wanderers' 'Bradford City' '1. FC Magdeburg'
 'FC Admira Wacker Mödling' 'Hamilton Academical FC' 'Aragua FC'
 'Accrington Stanley' 'Swindon Town' 'Carlisle United' 'FC Argeș'
 'Port Vale' 'Academica Clinceni' 'Rochdale' 'Gillingham'
 'Tranmere Rovers' 'Southend United' '1. FC Saarbrücken'
 'Colchester United' 'Mansfield Town' 'Falkenbergs FF' 'SC Verl'
 'Varbergs BoIS' 'Crawley Town' 'Sandefjord Fotball' 'Newport County'
 'Bohemian FC' 'Ross County FC' 'Scunthorpe United' 'Morecambe' 'Walsall'
 'Leyton Orient' 'Stevenage' 'Barrow' 'Derry City' 'Llaneros de Guanare'
 'Sligo Rovers' 'Zamora FC' "St. Patrick's Athletic" 'Cork City'
 'Shelbourne FC' 'Harrogate Town' 'Waterford FC' 'Finn Harps']

In [18]:
# 1. Check the current data type
print(f"Current Type: {df['Joined'].dtype}")

# 2. Convert to Datetime
df['Joined'] = pd.to_datetime(df['Joined'])

# 3. Verify the change
print(f"New Type: {df['Joined'].dtype}")

# 4. Check the actual values to ensure they look like dates (YYYY-MM-DD)
print(df['Joined'].head())

Current Type: object
New Type: datetime64[ns]
0   2004-07-01
1   2018-07-10
2   2014-07-16
3   2015-08-30
4   2017-08-03
Name: Joined, dtype: datetime64[ns]

In [19]:
# 1. Convert to Datetime
df['Loan Date End'] = pd.to_datetime(df['Loan Date End'], errors='coerce')

# errors='coerce' is crucial here. It tells Pandas: "If you find something that isn't a date, just turn it into NaT (Not a Time) instead of crashing."

# 2. Verify the Change
print(df[df['Loan Date End'].notna()]['Loan Date End'].head())

# 3. Check the Data Type
print(f"New Type: {df['Loan Date End'].dtype}")

205   2021-06-30
248   2021-06-30
254   2021-06-30
302   2021-06-30
306   2021-06-30
Name: Loan Date End, dtype: datetime64[ns]
New Type: datetime64[ns]

In [20]:
df['Loan Date End'].head()

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: Loan Date End, dtype: datetime64[ns]

In [21]:
#Redundant Columns: The Contract column duplicates information available in Joined and Contract Valid Until, 
#and requires parsing to be useful.

# 1. Define a function to parse the text
def extract_contract_info(contract):
    # Handle empty or 'Free' contracts
    if pd.isna(contract) or contract == 'Free':
        return np.nan, np.nan
    
    # Handle Loan players
    if 'On Loan' in contract:
        return np.nan, np.nan
    
    # Handle Standard "2018 ~ 2024" format
    if '~' in contract:
        start, end = contract.split(' ~ ')
        return int(start), int(end)
    
    # Default fallback
    return np.nan, np.nan

# 2. Apply the function

df['Contract_Start'], df['Contract_End'] = zip(*df['Contract'].apply(extract_contract_info))

# 3. Verify the results
# Look at the original column vs. the new columns

print(df[['Contract', 'Contract_Start', 'Contract_End']].head())

# 4. Check data types (Should be float because NaNs force integers to become floats)

print(df[['Contract_Start', 'Contract_End']].dtypes)

      Contract  Contract_Start  Contract_End
0  2004 ~ 2021          2004.0        2021.0
1  2018 ~ 2022          2018.0        2022.0
2  2014 ~ 2023          2014.0        2023.0
3  2015 ~ 2023          2015.0        2023.0
4  2017 ~ 2022          2017.0        2022.0
Contract_Start    float64
Contract_End      float64
dtype: object

In [22]:
# Drop the 'Contract' column
df = df.drop(columns=['Contract'])

In [23]:
df.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,Positions,Height_cm,Weight_kg,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract_Start,Contract_End
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,FC Barcelona,"RW, ST, CF",170,72,Left,93,RW,2004-07-01,NaT,103500000.0,560000.0,138400000.0,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4,4,Medium,Low,5,85,92,91,95,38,65,771,2004.0,2021.0
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,Juventus,"ST, LW",187,83,Right,92,ST,2018-07-10,NaT,63000000.0,220000.0,75900000.0,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4,5,High,Low,5,89,93,81,89,35,77,562,2018.0,2022.0
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,Atlético Madrid,GK,188,87,Right,91,GK,2014-07-16,NaT,120000000.0,125000.0,159400000.0,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3,1,Medium,Medium,3,87,92,78,90,52,90,150,2014.0,2023.0
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,Manchester City,"CAM, CM",181,70,Right,91,CAM,2015-08-30,NaT,129000000.0,370000.0,161000000.0,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5,4,High,High,4,76,86,93,88,64,78,207,2015.0,2023.0
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,Paris Saint-Germain,"LW, CAM",175,68,Right,91,LW,2017-08-03,NaT,132000000.0,270000.0,166500000.0,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5,5,High,Medium,5,91,85,86,94,36,59,595,2017.0,2022.0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 78 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Positions         18979 non-null  object
 11  Height_cm         18979 non-null  int64
 12  Weight_kg         18979 non-null  int64
 13  Preferred Foot    18979 non-null  object
 14  BOV               18979 non-null  int64
 15  Best Position     18979 non-null  object
 16  Joined            18979 non-null  datetime64[ns]
 17  Loan Date End     1013 non-null   datetime64[ns]
 18  Value             18979 non-null  float64
 19  Wage              18979 non-null  float64
 20  Release Clause    18979 non-null  float64
 21  Attacking         18979 non-null  int64
 22  Crossing          18979 non-null  int64
 23  Finishing         18979 non-null  int64
 24  Heading Accuracy  18979 non-null  int64
 25  Short Passing     18979 non-null  int64
 26  Volleys           18979 non-null  int64
 27  Skill             18979 non-null  int64
 28  Dribbling         18979 non-null  int64
 29  Curve             18979 non-null  int64
 30  FK Accuracy       18979 non-null  int64
 31  Long Passing      18979 non-null  int64
 32  Ball Control      18979 non-null  int64
 33  Movement          18979 non-null  int64
 34  Acceleration      18979 non-null  int64
 35  Sprint Speed      18979 non-null  int64
 36  Agility           18979 non-null  int64
 37  Reactions         18979 non-null  int64
 38  Balance           18979 non-null  int64
 39  Power             18979 non-null  int64
 40  Shot Power        18979 non-null  int64
 41  Jumping           18979 non-null  int64
 42  Stamina           18979 non-null  int64
 43  Strength          18979 non-null  int64
 44  Long Shots        18979 non-null  int64
 45  Mentality         18979 non-null  int64
 46  Aggression        18979 non-null  int64
 47  Interceptions     18979 non-null  int64
 48  Positioning       18979 non-null  int64
 49  Vision            18979 non-null  int64
 50  Penalties         18979 non-null  int64
 51  Composure         18979 non-null  int64
 52  Defending         18979 non-null  int64
 53  Marking           18979 non-null  int64
 54  Standing Tackle   18979 non-null  int64
 55  Sliding Tackle    18979 non-null  int64
 56  Goalkeeping       18979 non-null  int64
 57  GK Diving         18979 non-null  int64
 58  GK Handling       18979 non-null  int64
 59  GK Kicking        18979 non-null  int64
 60  GK Positioning    18979 non-null  int64
 61  GK Reflexes       18979 non-null  int64
 62  Total Stats       18979 non-null  int64
 63  Base Stats        18979 non-null  int64
 64  W/F               18979 non-null  int64
 65  SM                18979 non-null  int64
 66  A/W               18979 non-null  object
 67  D/W               18979 non-null  object
 68  IR                18979 non-null  int64
 69  PAC               18979 non-null  int64
 70  SHO               18979 non-null  int64
 71  PAS               18979 non-null  int64
 72  DRI               18979 non-null  int64
 73  DEF               18979 non-null  int64
 74  PHY               18979 non-null  int64
 75  Hits              16384 non-null  object
 76  Contract_Start    17729 non-null  float64
 77  Contract_End      17729 non-null  float64
dtypes: datetime64[ns](2), float64(5), int64(59), object(12)
memory usage: 11.3+ MB

In [25]:
# 1. Clean the 'Hits' column
def clean_hits(hits):
    if pd.isna(hits):
        return 0 # Assume 0 hits if missing
    
    hits = str(hits) # Ensure string
    
    if 'K' in hits:
        hits = hits.replace('K', '')
        return float(hits) * 1000
    else:
        return float(hits)

df['Hits'] = df['Hits'].apply(clean_hits)

# 2. Drop the mostly empty 'Loan Date End' column

df = df.drop(columns=['Loan Date End'])

In [26]:
# Drop Personal Info Columns (Privacy/Irrelevance)
# We don't need URLs or IDs for statistical analysis

cols_to_drop = ['photoUrl', 'playerUrl', 'ID', 'LongName']
df = df.drop(columns=cols_to_drop)

# Final Verify
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 73 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              18979 non-null  object
 1   Nationality       18979 non-null  object
 2   Age               18979 non-null  int64
 3   ↓OVA              18979 non-null  int64
 4   POT               18979 non-null  int64
 5   Club              18979 non-null  object
 6   Positions         18979 non-null  object
 7   Height_cm         18979 non-null  int64
 8   Weight_kg         18979 non-null  int64
 9   Preferred Foot    18979 non-null  object
 10  BOV               18979 non-null  int64
 11  Best Position     18979 non-null  object
 12  Joined            18979 non-null  datetime64[ns]
 13  Value             18979 non-null  float64
 14  Wage              18979 non-null  float64
 15  Release Clause    18979 non-null  float64
 16  Attacking         18979 non-null  int64
 17  Crossing          18979 non-null  int64
 18  Finishing         18979 non-null  int64
 19  Heading Accuracy  18979 non-null  int64
 20  Short Passing     18979 non-null  int64
 21  Volleys           18979 non-null  int64
 22  Skill             18979 non-null  int64
 23  Dribbling         18979 non-null  int64
 24  Curve             18979 non-null  int64
 25  FK Accuracy       18979 non-null  int64
 26  Long Passing      18979 non-null  int64
 27  Ball Control      18979 non-null  int64
 28  Movement          18979 non-null  int64
 29  Acceleration      18979 non-null  int64
 30  Sprint Speed      18979 non-null  int64
 31  Agility           18979 non-null  int64
 32  Reactions         18979 non-null  int64
 33  Balance           18979 non-null  int64
 34  Power             18979 non-null  int64
 35  Shot Power        18979 non-null  int64
 36  Jumping           18979 non-null  int64
 37  Stamina           18979 non-null  int64
 38  Strength          18979 non-null  int64
 39  Long Shots        18979 non-null  int64
 40  Mentality         18979 non-null  int64
 41  Aggression        18979 non-null  int64
 42  Interceptions     18979 non-null  int64
 43  Positioning       18979 non-null  int64
 44  Vision            18979 non-null  int64
 45  Penalties         18979 non-null  int64
 46  Composure         18979 non-null  int64
 47  Defending         18979 non-null  int64
 48  Marking           18979 non-null  int64
 49  Standing Tackle   18979 non-null  int64
 50  Sliding Tackle    18979 non-null  int64
 51  Goalkeeping       18979 non-null  int64
 52  GK Diving         18979 non-null  int64
 53  GK Handling       18979 non-null  int64
 54  GK Kicking        18979 non-null  int64
 55  GK Positioning    18979 non-null  int64
 56  GK Reflexes       18979 non-null  int64
 57  Total Stats       18979 non-null  int64
 58  Base Stats        18979 non-null  int64
 59  W/F               18979 non-null  int64
 60  SM                18979 non-null  int64
 61  A/W               18979 non-null  object
 62  D/W               18979 non-null  object
 63  IR                18979 non-null  int64
 64  PAC               18979 non-null  int64
 65  SHO               18979 non-null  int64
 66  PAS               18979 non-null  int64
 67  DRI               18979 non-null  int64
 68  DEF               18979 non-null  int64
 69  PHY               18979 non-null  int64
 70  Hits              18979 non-null  float64
 71  Contract_Start    17729 non-null  float64
 72  Contract_End      17729 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(58), object(8)
memory usage: 10.6+ MB
None

In [27]:
from datetime import datetime

df['Joined'] = pd.to_datetime(df['Joined'], errors='coerce')

# Extract useful info

df['Joined_year'] = df['Joined'].dt.year

current_year = datetime.now().year

df['Years_at_club'] = current_year - df['Joined_year']

df = df.drop(columns=['Joined'])

### 🧹 Data Preprocessing (Handling Missing Values, Encoding, and Scaling)

After identifying data quality issues, it is essential to preprocess the dataset to make it suitable for Machine Learning models.
Handling Missing Values
Missing data can lead to errors or biased predictions if not addressed properly. Filling missing values ensures that the model can learn from a complete dataset without discarding useful information.
Encoding Categorical Variables
Machine Learning models cannot work with categorical data directly. Encoding transforms categorical features (such as player position or club) into numerical form, allowing the model to interpret and learn patterns from them.
Feature Scaling
Features in the dataset exist on different scales (e.g., wages in millions vs ratings out of 100). Scaling ensures that no single feature dominates the model due to its magnitude, leading to more stable and accurate predictions.
These steps help standardize the dataset, reduce bias, and improve overall model performance.

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 74 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              18979 non-null  object
 1   Nationality       18979 non-null  object
 2   Age               18979 non-null  int64
 3   ↓OVA              18979 non-null  int64
 4   POT               18979 non-null  int64
 5   Club              18979 non-null  object
 6   Positions         18979 non-null  object
 7   Height_cm         18979 non-null  int64
 8   Weight_kg         18979 non-null  int64
 9   Preferred Foot    18979 non-null  object
 10  BOV               18979 non-null  int64
 11  Best Position     18979 non-null  object
 12  Value             18979 non-null  float64
 13  Wage              18979 non-null  float64
 14  Release Clause    18979 non-null  float64
 15  Attacking         18979 non-null  int64
 16  Crossing          18979 non-null  int64
 17  Finishing         18979 non-null  int64
 18  Heading Accuracy  18979 non-null  int64
 19  Short Passing     18979 non-null  int64
 20  Volleys           18979 non-null  int64
 21  Skill             18979 non-null  int64
 22  Dribbling         18979 non-null  int64
 23  Curve             18979 non-null  int64
 24  FK Accuracy       18979 non-null  int64
 25  Long Passing      18979 non-null  int64
 26  Ball Control      18979 non-null  int64
 27  Movement          18979 non-null  int64
 28  Acceleration      18979 non-null  int64
 29  Sprint Speed      18979 non-null  int64
 30  Agility           18979 non-null  int64
 31  Reactions         18979 non-null  int64
 32  Balance           18979 non-null  int64
 33  Power             18979 non-null  int64
 34  Shot Power        18979 non-null  int64
 35  Jumping           18979 non-null  int64
 36  Stamina           18979 non-null  int64
 37  Strength          18979 non-null  int64
 38  Long Shots        18979 non-null  int64
 39  Mentality         18979 non-null  int64
 40  Aggression        18979 non-null  int64
 41  Interceptions     18979 non-null  int64
 42  Positioning       18979 non-null  int64
 43  Vision            18979 non-null  int64
 44  Penalties         18979 non-null  int64
 45  Composure         18979 non-null  int64
 46  Defending         18979 non-null  int64
 47  Marking           18979 non-null  int64
 48  Standing Tackle   18979 non-null  int64
 49  Sliding Tackle    18979 non-null  int64
 50  Goalkeeping       18979 non-null  int64
 51  GK Diving         18979 non-null  int64
 52  GK Handling       18979 non-null  int64
 53  GK Kicking        18979 non-null  int64
 54  GK Positioning    18979 non-null  int64
 55  GK Reflexes       18979 non-null  int64
 56  Total Stats       18979 non-null  int64
 57  Base Stats        18979 non-null  int64
 58  W/F               18979 non-null  int64
 59  SM                18979 non-null  int64
 60  A/W               18979 non-null  object
 61  D/W               18979 non-null  object
 62  IR                18979 non-null  int64
 63  PAC               18979 non-null  int64
 64  SHO               18979 non-null  int64
 65  PAS               18979 non-null  int64
 66  DRI               18979 non-null  int64
 67  DEF               18979 non-null  int64
 68  PHY               18979 non-null  int64
 69  Hits              18979 non-null  float64
 70  Contract_Start    17729 non-null  float64
 71  Contract_End      17729 non-null  float64
 72  Joined_year       18979 non-null  int32
 73  Years_at_club     18979 non-null  int32
dtypes: float64(6), int32(2), int64(58), object(8)
memory usage: 10.6+ MB

### 💾 Exporting Cleaned Dataset

In [29]:
df.to_csv("cleaned_fifa.csv", index=False)